using Compat, LibFTD2XX
devs = FT_CreateDeviceInfoList()
list, elnum = FT_GetDeviceInfoList(devs)
description = String(list[3].description)
handle = open(description, OPEN_BY_DESCRIPTION)
datacharacteristics(handle)
baudrate(handle,2000000)
write(handle, Vector{UInt8}(codeunits("hello")))
String(read(handle, 5))
close(handle)